### ISSUE TITLE
Social Links are not redirecting anywhere

### ISSUE THREAD

**Issue by mohit-1710** [Anshul439/Blogverse#11]
![image](https://github.com/user-attachments/assets/d493e9dd-a932-4d8b-89bf-74ae02d0fbfc)
The social links in the footer section are not redirecting properly. When I hover over the GitHub icon, it takes me to the top of the page instead of redirecting to the correct URL.

For example, the GitHub link should redirect to: https://github.com/Anshul439/Blogverse.

Also, @Anshul439, please provide the social media links for "Blogverse" so we can update the footer links accordingly.

**Comment by mohit-1710** [comment]
Please assign it to me i am willing to work on this

**Comment by saarakhan** [comment]
I would like to work on this issue please assign this to me :)
