### ISSUE TITLE
Error on Editing Blog Post: Missing Post ID Leads to Update Failure

### ISSUE THREAD

**Issue by VanshChitransh** [Anshul439/Blogverse#12]
# Issue: Unable to Edit Blog Post - Missing Post ID

### Description:
After publishing a blog post, users are unable to edit the post. The update process fails, and the following error is observed:

This error indicates that the `_id` of the post is not properly passed in the PUT request to update the post.

### Steps to Reproduce:
1. Write and publish a blog post.
2. Attempt to edit the published post using the "Update Post" feature.
3. Observe the failed PUT request and error in the console.

### Error Logs:
- **Console Error:** 

![Screenshot from 2024-10-04 01-24-15](https://github.com/user-attachments/assets/6820c28a-c5a8-40b9-ac8c-0a64ac517ab1)

### Impact:
- Users are unable to edit their published posts, which disrupts content management.

### Possible Cause:
- The post `_id` is missing or set to `undefined` in the PUT request URL, likely due to incorrect state handling or failure to pass the post ID in the frontend.

### Proposed Solution:
1. **Frontend Fix:**
 - Ensure the correct `_id` of the post is passed when initiating the PUT request.
 - Check that the component responsible for post updates retrieves and maintains the post ID properly during the edit process.

2. **Backend Validation:**
 - Add validation in the backend to check if the `_id` is present in the request. Return an appropriate error message if the `_id` is missing.

---

### Priority: 
High

### Status: 
Open

**Comment by VanshChitransh** [comment]
@Anshul439 I would love to work on this issue.

**Comment by Anshul439** [comment]
Go ahead.

**Comment by VanshChitransh** [comment]
@Anshul439 I will update you on all the features/issues in few time.
