### ISSUE TITLE
Inadequate Password Length Restrictions

### ISSUE THREAD

**Issue by mohit-1710** [Anshul439/Blogverse#20]
# Issue: Password Length Validation Too Short

## Description
The current password validation on both login and signup forms allows passwords of length 1 or 2. This compromises the security of the application, as short passwords are highly vulnerable to brute-force attacks.

## Expected Behavior
- Password length should have a minimum requirement (typically 8 characters) for both the login and signup forms.
- The system should reject passwords that do not meet the required length and display an appropriate error message to the user.

## Actual Behavior
- The system accepts passwords of length 1 or 2 without any validation.
- No error message is shown, and the user is able to proceed with the login or signup using a weak password.

##Screenshot:
![Screenshot from 2024-10-04 13-14-34](https://github.com/user-attachments/assets/b0ead49b-c026-4881-a9a6-a113c30ac011)

## Steps to Reproduce
1. Go to the signup or login page.
2. Enter a password with only 1 or 2 characters.
3. Submit the form.
4. Notice that the form accepts the password without any validation error.

## Possible Fix
Implement a password validation rule that enforces a minimum password length of 8 characters. Additionally, the system should notify users if their password is too short during the signup or login process.

## Environment
- **Repository:** Blogverse
- **Browser:** Brave/Chrome
- **Operating System:** Linux

## Additional Context
This issue severely impacts the security of the application by allowing users to create weak passwords, potentially leading to data breaches.

**Comment by mohit-1710** [comment]
@Anshul439 I would be happy to work on this issue.

**Comment by namansharma3007** [comment]
@Anshul439 Please assign this issue to me. I have worked passwords.

**Comment by Anshul439** [comment]
> @Anshul439 I would be happy to work on this issue.

Go ahead.
