### ISSUE TITLE
Feature Request: Add "Forgot Password" Button with Email Reset Functionality

### ISSUE THREAD

**Issue by mohit-1710** [Anshul439/Blogverse#37]
### Description

I would like to request a new feature that adds a "Forgot Password" button just below the sign-in form. This feature would allow users to reset their password via an authentication email containing a password reset link.

### Proposed Feature Details

- Add a **"Forgot Password"** button below the **Sign In** form.
- When clicked, users will be prompted to enter their email address.
- An email will be sent to the user containing a unique link to reset their password.
- The link will redirect the user to a password reset page where they can securely create a new password.
- Add validation to ensure the email exists in the database before sending the reset link.

### Benefits

- Improves the user experience by allowing users to easily recover their accounts in case they forget their password.
- Enhances account security by enabling a secure password reset process through email.
- Reduces support inquiries related to account access issues due to forgotten passwords.

### Potential Implementation Steps

1. Add a "Forgot Password" button to the **Sign In** page.
2. Create an API endpoint to handle password reset requests (e.g., `/api/auth/forgot-password`).
3. Generate a unique, time-limited token when the user requests a password reset.
4. Send an email to the user with a link to reset their password (e.g., `/reset-password?token=<unique-token>`).
5. Create a **Reset Password** page where the user can input a new password.
6. Validate the token and ensure the new password meets security requirements (e.g., length).
7. Update the user's password in the database after successful validation.

### References

- Similar implementations in popular web platforms (e.g., GitHub, Gmail) for password recovery.
- Documentation on secure password reset flows.

### Additional Context

Implementing this feature will improve the user account management experience and provide an additional layer of security. Feel free to ask for more details or clarification!

**Comment by mohit-1710** [comment]
@Anshul439 please assign this issue to me .

**Comment by Anshul439** [comment]
This issue has already been raised
