### ISSUE TITLE
Enhance User Experience: Add Eye Icon to Toggle Password Visibility

### ISSUE THREAD

**Issue by Shreyhac** [Anshul439/Blogverse#53]
Currently, users cannot see the password they are typing when signing in. To enhance the user experience and prevent typing errors, adding an eye icon next to the password field that allows users to toggle password visibility is a simple yet effective feature.

Steps to Reproduce:
Navigate to the login page.
Enter text in the password field.
Notice that there is no option to show or hide the password.
Expected Behavior:
A small eye icon should appear next to the password input field.
When the user clicks the eye icon, the password should toggle between hidden and visible text.
Clicking the eye icon again should hide the password.
Actual Behavior:
There is no current option to view the password while typing, which can lead to potential errors in password entry.
Suggested Solution:
Implement an eye icon button within the password input field.
The button should toggle the password field between type="password" and type="text" to reveal or hide the password.
<img width="1470" alt="Screenshot 2024-10-16 at 02 00 17" src="https://github.com/user-attachments/assets/661cc34c-4d87-4125-9167-4b0af0185046">

**Comment by Shreyhac** [comment]
please assign me this under hactoberfest

**Comment by Anshul439** [comment]
This issue has already been opened
