### ISSUE TITLE
Enhancement : Making the navbar sticky to enhance UI

### ISSUE THREAD

**Issue by 1-SubhamSingh** [Anshul439/Blogverse#7]
I'll complete this task , can you please assign this task to me under the Hacktoberfest2024 label :)

**Comment by MuskanPastor** [comment]
I want to work on this issue @Anshul439

**Comment by Anshul439** [comment]
> I'll complete this task , can you please assign this task to me under the Hacktoberfest2024 label :)

I don't think there is any need of that for now. Will open this issue in future if needed.
